#---------------------------------------------#
#       build/environment configuration       #
#---------------------------------------------#

version: '{build}'

build:
  project: Repositive.sln
  verbosity: minimal

image: Visual Studio 2019
configuration: Release
platform: Any CPU

cache:
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

environment:
  private_key_pass:
    secure: vOCLLinDZ51qdMw/T43JH1w4v2bWbdMVfEGCnC2il/c=

#-------------------------------------#
#       pre-build configuration       #
#-------------------------------------#

before_build:
  - ps: |
        $props = ([xml](Get-Content "Directory.Build.props")).Project.PropertyGroup
        $vPrefix = $props.VersionPrefix
        $vSuffix = $props.VersionSuffix
        $releaseNotes = if ($props.PackageReleaseNotes.GetType() -eq [System.Xml.XmlElement]) { $props.PackageReleaseNotes.InnerText } else { $props.PackageReleaseNotes }
        
        $env:fullVersion = @{ $true = "$($vPrefix)-$($vSuffix)"; $false = $($vPrefix) }[-not ([string]::IsNullOrEmpty($vSuffix))]
        $env:isPreRelease = @{ $true = "true"; $false = "false" }[-not ([string]::IsNullOrEmpty($vSuffix))]
        $env:releaseNotes = @{ $true = $releaseNotes.Replace("`n", '\n').TrimEnd().Trim('\n'); $false = "$env:fullVersion release!" }[-not ([string]::IsNullOrEmpty($releaseNotes))]
        
        Update-AppveyorBuild -Version "$env:fullVersion Build-$env:APPVEYOR_BUILD_VERSION"

  - ps: dotnet restore

  - ps: |
        Import-PfxCertificate -FilePath RepositiveKey.pfx -CertStoreLocation cert:\CurrentUser\VS_KEY_689BEEB655EEA138 -Password (ConvertTo-SecureString -String $env:private_key_pass -Force –AsPlainText)

#-----------------------------------------#
#       build trigger configuration       #
#-----------------------------------------#

skip_commits:
  files:
    - '**/*.md'
    - 'license'

skip_tags: false

#-----------------------------------#
#       publish configuration       #
#-----------------------------------#

nuget:
  disable_publish_on_pr: true

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: Repositive.Abstractions/bin/$(configuration)/Binaries
    name: Repositive.Abstractions.$(fullVersion)
    type: zip

  - path: Repositive.EntityFrameworkCore/bin/$(configuration)/Binaries
    name: Repositive.EntityFrameworkCore.$(fullVersion)
    type: zip

  - path: Repositive.Abstractions/bin/$(configuration)/Package/*.nupkg
  - path: Repositive.EntityFrameworkCore/bin/$(configuration)/Package/*.nupkg

#---------------------------------#
#      deploy configuration       #
#---------------------------------#

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: $(releaseNotes)
    draft: false
    prerelease: $(isPreRelease)
    auth_token:
      secure: 17uIp5Xz3DUfAUcfU6n/DajZ45rm5HVKrhTYVYJ4Z8XocWZvtSzhfZTfak6P6emy
    on:
      APPVEYOR_REPO_TAG: true

  - provider: NuGet
    api_key:
      secure: pF8W2j/TXfR8dLUpvBIabRDxkz0ye8u+cCQrsWOczf5C6QiyRKWY8M6dvbW1fAcK
    on:
      APPVEYOR_REPO_TAG: true