#---------------------------------------------#
#       build/environment configuration       #
#---------------------------------------------#

version: '{build}'

build:
  project: Repositive.sln
  verbosity: minimal

image: Visual Studio 2019
configuration: Release
platform: Any CPU

cache:
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

#-------------------------------------#
#       pre-build configuration       #
#-------------------------------------#

before_build:
  - ps: |
        $props = ([xml](Get-Content "Directory.Build.props")).Project.PropertyGroup
        $vPrefix = $props.VersionPrefix
        $vSuffix = $props.VersionSuffix
        $releaseNotes = $props.PackageReleaseNotes
        
        $env:fullVersion = @{ $true = "$($vPrefix)-$($vSuffix)"; $false = $($vPrefix) }[-not ([string]::IsNullOrEmpty($vSuffix))]
        $env:isPreRelease = @{ $true = "true"; $false = "false" }[-not ([string]::IsNullOrEmpty($vSuffix))]
        $env:releaseNotes = @{ $true = "$releaseNotes"; $false = "$env:fullVersion release!" }[-not ([string]::IsNullOrEmpty($releaseNotes))]
        
        Update-AppveyorBuild -Version "$env:fullVersion Build-$env:APPVEYOR_BUILD_VERSION"

  - ps: dotnet restore

after_build :
  - ps: Write-Host $env:releaseNotes

#-----------------------------------------#
#       build trigger configuration       #
#-----------------------------------------#

skip_commits:
  files:
    - '**/*.md'
    - 'license'

skip_tags: false

#-----------------------------------#
#       publish configuration       #
#-----------------------------------#

for:
-
  branches:
    except:
      - master

  build:
    publish_nuget: false

nuget:
  disable_publish_on_pr: true

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: Repositive.Abstractions/bin/$(configuration)/Binaries
    name: Repositive.Abstractions
    type: zip

  - path: Repositive.EntityFrameworkCore/bin/$(configuration)/Binaries
    name: Repositive.EntityFrameworkCore
    type: zip

  - path: Repositive.Abstractions/bin/$(configuration)/Package/*.nupkg
  - path: Repositive.EntityFrameworkCore/bin/$(configuration)/Package/*.nupkg

#---------------------------------#
#      deploy configuration       #
#---------------------------------#

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: $(releaseNotes)
    draft: false
    prerelease: $(isPreRelease)
    auth_token:
      secure: 17uIp5Xz3DUfAUcfU6n/DajZ45rm5HVKrhTYVYJ4Z8XocWZvtSzhfZTfak6P6emy
    on:
      APPVEYOR_REPO_TAG: true

  - provider: NuGet
    api_key:
      secure: pF8W2j/TXfR8dLUpvBIabRDxkz0ye8u+cCQrsWOczf5C6QiyRKWY8M6dvbW1fAcK
    on:
      APPVEYOR_REPO_TAG: true